#limit.type: local
#limit.type: redis
#
#spring:
#  redis:
#    host: localhost
#    port: 6379
##    password: ee
#    database: 1
#    pool:
#      max-active: 8
#      max-wait: -1
#      max-idle: 500
#      min-idle: 0
#    timeout: 0

limit.type: local
limit.filter: true
limit.rule.url.num: 100
limit.rule.url.seconds: 2
limit.rule.user.num: 100
limit.rule.user.seconds: 10
limit.rule.user_url.num: 100
limit.rule.user_url.seconds: 10
limit.rule.identifier.key: userId
